[package]
name = "btpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noodles-bed = "0.2.0"
parquet = "11.1.0"
parquet_derive = "11.1.0"

[dev-dependencies]
noodles-core = "0.6.0"
